dev

diff --git a/.github/workflows/test-native-2.yml b/.github/workflows/test-native-2.yml
--- a/.github/workflows/test-native-2.yml
+++ b/.github/workflows/test-native-2.yml
@@ -73,13 +73,19 @@ jobs:
           echo "Available simulators: $AVAILABLE_SIMULATORS"
 
           SELECTED_SIMULATOR=$(echo $AVAILABLE_SIMULATORS | jq -r "[.[] | select(.runtime | contains(\"$SIMULATOR_IOS_VERSION\")) | select(.name | \"$SIMULATOR_DEVICE_NAME\")] | first")
-
           if [ -z "$SELECTED_SIMULATOR" ] || [ "$SELECTED_SIMULATOR" = "null" ]; then
             echo "Error: No simulator found for iOS version $SIMULATOR_IOS_VERSION and device name $SIMULATOR_DEVICE_NAME"
             exit 1
           fi
-
           echo "Selected simulator: $SELECTED_SIMULATOR"
+
+          SIMULATOR_UDID=$(echo $SELECTED_SIMULATOR | jq -r .udid)
+          if [ -z "$SIMULATOR_UDID" ] || [ "$SIMULATOR_UDID" = "null" ]; then
+            echo "Error: Could not get simulator UDID"
+            exit 1
+          fi
+          echo "Simulator UDID: $SIMULATOR_UDID"
+          echo "simulator_udid=$SIMULATOR_UDID" >> $GITHUB_OUTPUT
 
       - name: Boot Simulator
         env:
@@ -101,7 +107,7 @@ jobs:
         with:
           name: appium.log
           path: |
-            /tmp/appium.log &
+            /tmp/appium.log
 
       # - name: Patch Packages
       #   run: |
